/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */


using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Crtk
{
    public class StringStamped : Message
    {
        public const string RosMessageName = "crtk_msgs/StringStamped";

        // 
        //  See https://github.com/collaborative-robotics/documentation/wiki/Robot-API-status
        // 
        //  Standard states include DISABLED, ENABLED, PAUSED and FAULT
        // 
        public Header header { get; set; }
        public string String { get; set; }

        public StringStamped()
        {
            this.header = new Header();
            this.String = "";
        }

        public StringStamped(Header header, string String)
        {
            this.header = header;
            this.String = String;
        }
    }
}
